version: '2'
services:
  db:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    volumes:
      - ../mariadb_10_1_17:/src
      - ../mariadb_10_1_17/lib:/var/lib/mysql
      - ../mariadb_10_1_17/log:/var/log/mysql
      - ../mariadb_10_1_17/bak:/var/backups/mysql
    # environment:
    #   - MYSQL_ROOT_PASSWORD=rootpassword
