#!/bin/sh

if [ -f "/src/_init.sql" ]; then
	echo "[RUNNING DEFAULT SQL FILE]"
	# Drop all tables in database
	mysqldump -u"$MYSQL_USER_NAME" -p"$MYSQL_USER_PASSWORD" --add-drop-table --no-data mydb | grep ^DROP | mysql -u"$MYSQL_USER_NAME" -p"$MYSQL_USER_PASSWORD" mydb
	printf "\033c"; echo "************************************************"
	mysql -u"$MYSQL_USER_NAME" -p"$MYSQL_USER_PASSWORD" mydb < main.sql
else
	echo "[RUNNING INIT SQL FILE]"
	# create _init.sql file
	touch "_init.sql"
	echo "CREATE DATABASE mydb;" >> _init.sql
	echo "USE mydb;" >> _init.sql
	echo "DROP DATABASE test;" >> _init.sql
	echo "update mysql.user set Password=PASSWORD('$MYSQL_USER_PASSWORD') where User='$MYSQL_USER_NAME';" >> _init.sql
	echo "FLUSH PRIVILEGES;" >> _init.sql

	mysql test < _init.sql
	# Drop all tables in database
	mysqldump -u"$MYSQL_USER_NAME" -p"$MYSQL_USER_PASSWORD" --add-drop-table --no-data mydb | grep ^DROP | mysql -u"$MYSQL_USER_NAME" -p"$MYSQL_USER_PASSWORD" mydb
	printf "\033c"; echo "************************************************"
	mysql -u"$MYSQL_USER_NAME" -p"$MYSQL_USER_PASSWORD" mydb < main.sql
fi
