#!/bin/sh
printf "\033c"; echo "************************************************"
cd /src
 sh -c "source /src/main"
while inotifywait --quiet -e modify /src --recursive; do
	printf "\033c"; echo "************************************************"
	sh -c "source /src/main"
done
