#!/bin/sh
cd /src
npm install
echo '*****************************************'
node /src/main.js
while inotifywait --quiet -e modify /src --recursive --exclude "npm-debug.log"; do
	node /src/main.js
done
