#!/bin/sh
cd /src

# ************************************************
#
# wget https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz -O emsdk-portable.tar.gz
# gunzip emsdk-portable.tar.gz
# tar -xf emsdk-portable.tar
# cd emsdk_portable
# ./emsdk update
# ./emsdk install clang-incoming-64bit emscripten-incoming-64bit sdk-incoming-64bit
# ./emsdk activate clang-incoming-64bit emscripten-incoming-64bit sdk-incoming-64bit
# source ./emsdk_env.sh
# cd ..
# ************************************************

source main
while inotifywait --quiet -e modify /src --recursive; do
	source main
done
