#!/bin/sh
go get github.com/tobyhede/go-underscore
echo "*********************** $GOPATH"
cd /src
rm /src/main
go build -o /src/main
/src/main
while inotifywait --quiet -e modify /src --recursive; do
	rm /src/main
	go build -o /src/main
	/src/main
done
