#!/bin/bash
imagePrefix=bash4342
imageId=sv
clean(){
	echo "CLEAN"
	# Stop and Remove Containers, Remove Images
	docker stop "$imagePrefix"_"$imageId"_1
	docker rm "$imagePrefix"_"$imageId"_1
	docker rmi "$imagePrefix"_"$imageId":latest
}

save(){
	echo "SAVE"
	rm "/$DOCKER_IMAGE_PATH/$imagePrefix.tar.gz"
	docker-compose --file dev.yml build
	docker save $imagePrefix"_"$imageId | gzip -9 >  "/$DOCKER_IMAGE_PATH/$imagePrefix.tar.gz"
}

load(){
	echo "LOAD"
	gzcat "/$DOCKER_IMAGE_PATH/$imagePrefix.tar.gz" | docker load
	docker-compose -f ./dev.yml up
}

init(){
	echo "INIT"
	clean
	save
	clean
}

case $1 in
  # ---------------------------------------------------
	clean)
		clean
	;;
	init)
		init
	;;
	load)
		load
	;;
  # ---------------------------------------------------
  *|"")    echo "Run Utility: run <Command> [Arguments...]"
esac
