#!/bin/sh
imagePrefix=node

# Stop Containers
docker stop "$imagePrefix"_sv_1

# Remove Containers
docker rm "$imagePrefix"_sv_1

# Remove Images
docker rmi "$imagePrefix"_sv:latest

rm -rf ./src/node_modules
