#!/bin/sh
printf "\033c"; echo "************************************************"
node /src/main.js
while inotifywait --quiet -e modify /src --recursive --exclude "npm-debug.log"; do
	printf "\033c"; echo "************************************************"
	node /src/main.js
done
