#!/bin/sh
cd /src
rm /src/main
go build -o /src/main
printf "\033c"; echo "************************************************"
/src/main
while inotifywait --quiet -e modify /src --recursive; do
	rm /src/main
	go build -o /src/main
	printf "\033c"; echo "************************************************"
	/src/main
done
