version: '2'
services:
  db:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    volumes:
      - ../node_sql:/src
      - ../node_sql/lib.gen:/var/lib/mysql
      - ../node_sql/log.gen:/var/log/mysql
      - ../node_sql/bak.gen:/var/backups/mysql
    ports:
      - 8080:8080
      - 3306:3306
    environment:
      - HTTP_PORT=8080
      - MYSQL_PORT=3306
      - MYSQL_HOST=127.0.0.1
      - MYSQL_DATABASE=mydb
      - MYSQL_USER_NAME=
      - MYSQL_USER_PASSWORD=
